const ERRORS = {
  DEFAULT: "Something Went Wrong",
  SERVER: "Internal Server Error",
  NOT_FOUND: "Not Found",
  AUTHORIZED: "Unauthorized",
  RATE_LIMIT: "Rate Limit",
  NOT_ALLOWED: "You Don't Have Permission",
  BAD_REQUEST: "Bad Request",
  FORBIDDEN: "Forbidden",
  CONFLICT: "Conflict",
  GATEWAY_TIMEOUT: "Gateway Timeout",
  SERVICE_UNAVAILABLE: "Service Unavailable",
  METHOD_NOT_ALLOWED: "Method Not Allowed",
  PRECONDITION_FAILED: "Precondition Failed",
  UNSUPPORTED_MEDIA_TYPE: "Unsupported Media Type",
  REQUEST_TIMEOUT: "Request Timeout",
  UNPROCESSABLE_ENTITY: "Unprocessable Entity",
  PAYLOAD_TOO_LARGE: "Payload Too Large",
  URI_TOO_LONG: "URI Too Long",
  EXPECTATION_FAILED: "Expectation Failed",
  IM_A_TEAPOT: "I'm a teapot",
  INSUFFICIENT_STORAGE: "Insufficient Storage",
  LOOP_DETECTED: "Loop Detected",
  NOT_IMPLEMENTED: "Not Implemented",
  NETWORK_AUTHENTICATION_REQUIRED: "Network Authentication Required",
  RESOURCE_EXPIRED: "Resource Expired",
  RESOURCE_LOCKED: "Resource Locked",
  ACCOUNT_SUSPENDED: "Account Suspended",
  PASSWORD_EXPIRED: "Password Expired",
  TOKEN_EXPIRED: "Token Expired",
  SESSION_EXPIRED: "Session Expired",
  EMAIL_ALREADY_EXISTS: "Email Already Exists",
  USER_NOT_FOUND: "User Not Found",
  ACCOUNT_NOT_ACTIVE: "Account Not Active",
  INVALID_TOKEN: "Invalid Token",
  ACCOUNT_ALREADY_EXISTS: "Account Already Exists",
  LINK_EXPIRED: "Link Expired",
  FILE_TOO_LARGE: "File Too Large",
  FILE_TYPE_NOT_ALLOWED: "File Type Not Allowed",
  OPERATION_FAILED: "Operation Failed",
  DEPENDENCY_ERROR: "Dependency Error",
  CONFIGURATION_ERROR: "Configuration Error",
  RATE_LIMIT_EXCEEDED: "Rate Limit Exceeded",
  DATABASE_ERROR: "Database Error",
  API_LIMIT_EXCEEDED: "API Limit Exceeded",
  RESOURCE_NOT_FOUND: "Resource Not Found",
  TOKEN_NOT_FOUND: "Token Not Found",
  USER_ALREADY_LOGGED_IN: "User Already Logged In",
  ACTION_NOT_ALLOWED: "Action Not Allowed",
  EMAIL_ALREADY_REGISTERED: "Email Already Registered",
  SESSION_NOT_FOUND: "Session Not Found",
  ACCOUNT_LOCKED: "Account Locked",
  EMAIL_NOT_FOUND: "Email Not Found",
  OTP_EXPIRED: "OTP Expired",
  INVALID_OTP: "Invalid OTP",
  ACCESS_DENIED: "Access Denied",
  NO_CONTENT: "No Content",
  NO_RESULTS: "No Results Found",
  EMAIL_INVALID: "Invalid Email Address",
  SYSTEM_MAINTENANCE: "System Under Maintenance",
  FEATURE_NOT_AVAILABLE: "Feature Not Available",
  VERSION_NOT_SUPPORTED: "Version Not Supported",
  RESOURCE_UNAVAILABLE: "Resource Unavailable",
  UNAUTHORIZED_OPERATION: "Unauthorized Operation",
  OPERATION_NOT_ALLOWED: "Operation Not Allowed",
  SERVICE_ERROR: "Service Error",
  DATABASE_UNAVAILABLE: "Database Unavailable",
  CACHE_MISS: "Cache Miss",
  NETWORK_ERROR: "Network Error",
  CONFIG_NOT_FOUND: "Configuration Not Found",
  BUDGET_POSITIVE: "Budget Must Be Positive",
};

module.exports = { ERRORS };
