const ERROR_ADS_SERVICE = {
  TRENDING_ADS: "[TRENDING_ADS_SERVICE]",
  SCHEDULLING_ADS: "[SCHEDULLING_ADS_SERVICE]",
  NOT_FOUND: "[NOT_FOUND_ADS_SERVICE]",
  CREATE_AD: "[CREATE_AD_SERVICE]",
  UPDATE_AD: "[UPDATE_AD_SERVICE]",
  DELETE_AD: "[DELETE_AD_SERVICE]",
  GET_AD: "[GET_AD_SERVICE]",
  IMPRESSIONS_AD: "[IMPRESSIONS_AD_SERVICE]",
  CLICKS_AD: "[CLICKS_AD_SERVICE]",
  IS_BALANCE_SUFFICIENT_FOR_DAILY_BUDGET: "[IS_BALANCE_SUFFICIENT_FOR_DAILY_BUDGET_SERVICE]"
};

module.exports = { ERROR_ADS_SERVICE };
